/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfase;

import java.net.URL;
import java.util.Observer;
import javafx.beans.InvalidationListener;
import javafx.beans.Observable;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Martin
 */
public class vJuego extends javax.swing.JFrame implements Observer{

    PatronObserver PObserver;
    int NumS;
    
    public vJuego() {
        initComponents();
    }
    
    public vJuego(PatronObserver pPObserver) {
        PObserver = pPObserver;
        initComponents();
        JOptionPane.showMessageDialog(this, "<b>El Juego A Comenzado</b>", "¡Atender!", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void CargarImagenSorteada()
    {
        NumS = PObserver.getBolillaSorteada();
        
        URL Bola = this.getClass().getResource("/Imagenes/"+NumS+".png");  
        ImageIcon Imagen = new ImageIcon(Bola);  
  
       lblImagen.setIcon(Imagen);  
    }
    
    public void  CargarHistorial()
    {
        DefaultTableModel TablaHistorial =(DefaultTableModel) tblHistorialNum.getModel(); 
        
        TablaHistorial.addColumn(NumS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistorialNum = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        Pozo = new javax.swing.JLabel();
        lblPozo = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        asd = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        jLabel2.setText("Numero Sorteado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        tblHistorialNum.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        tblHistorialNum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Numeros Sorteados"
            }
        ));
        jScrollPane2.setViewportView(tblHistorialNum);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 520, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TituloBingo.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 330, 250));

        Pozo.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        Pozo.setText("Pozo");
        getContentPane().add(Pozo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        lblPozo.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        lblPozo.setText(".");
        getContentPane().add(lblPozo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 230, 160));

        asd.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        asd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        asd.setText(".");
        getContentPane().add(asd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pozo;
    private javax.swing.JLabel asd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPozo;
    private javax.swing.JTable tblHistorialNum;
    // End of variables declaration//GEN-END:variables

    
    
    @Override
    public void update(java.util.Observable o, Object arg) {
       if(PObserver.getGanador()==null)
        {
            if(PObserver.getVentanasJugando().size()>1) // se fija si alguien esta jugando solo
            {
                if(lblPozo.getText().toString().equals(".")||PObserver.getPozo()!=(Integer.parseInt(lblPozo.getText().toString())))
                {
                   lblPozo.setText(String.valueOf(PObserver.getPozo()));
                }
                else
                {
                    PObserver.getBolillaSorteada(); // si todo sigue normal, se busca si saco esa bolilla
                    CargarImagenSorteada();
                    CargarHistorial();
                }
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "El Juego A Finalizado");
        }
    }

}   
