/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfase;

import static Common.Utilidades.*;
import Common.cException;
import Common.cJuego;
import Common.cUsuario;
import Dominio.Bingo;
import static Dominio.Bingo.getInstancia;
import java.util.Observable;
import java.util.Observer;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class vJugador extends javax.swing.JFrame implements Observer{

    Bingo b = getInstancia();;
    cUsuario usu ;
    cJuego j;
            
    public vJugador(){}
            
    public vJugador(cUsuario pusu) throws cException {
        usu = pusu;
        j = b.buscarTodo();
        
        initComponents();
        
        // <editor-fold defaultstate="collapsed" desc=" Compra De Cartones ">
        String Resultado = "Testeando";
        while(Validar(Resultado) != EnumeradosVentana.Ok)
        {
            Resultado = (JOptionPane.showInputDialog(this, "¿Con Cuantos Cartones Jugara?", "1 -"+j.getCantidadMaximaCartonesXJuegadores()));
            if(Validar(Resultado) == EnumeradosVentana.Ok)
            {
                break;
            }
                
            if(Validar(Resultado) == EnumeradosVentana.NoNumero || Validar(Resultado) == EnumeradosVentana.NoValido){ 
               JOptionPane.showMessageDialog(this, "Ingrese Un Numero Entre"
                    + "\n 1 - "+ Integer.toString(VentanasAbiertas)); 
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Su Saldo No Es Suficiente");
                Resultado = "Testeando";
            }
        }
        // </editor-fold>
        
        ManejoTablas();
        VentanasLogueadas++;
        if(VentanasAbiertas==VentanasLogueadas)
        {
            b.ComenzarPartida();
        }
    }
    
    private EnumeradosVentana Validar(String pResultado) throws cException
    {
        if(!isNumeric(pResultado))
        {
            return EnumeradosVentana.NoNumero;
        }
        if(Integer.parseInt(pResultado)>j.getCantidadMaximaCartonesXJuegadores()&&Integer.parseInt(pResultado)<1)
        {
            return EnumeradosVentana.NoValido;
        }
        if(!b.CompraDeCarton(VentanasAbiertas, usu))
        {
            return EnumeradosVentana.NoSaldo;
        }
        return EnumeradosVentana.Ok;
    }
    
    public void ManejoTablas()
    {  /*      
        tblCarton1.setVisible(false);
        tblCarton2.setVisible(false);
        tblCarton3.setVisible(false);
        tblCarton4.setVisible(false);
        tblCarton5.setVisible(false);
        tblCarton6.setVisible(false);
        tblCarton7.setVisible(false);
        tblCarton8.setVisible(false);
     
        int CantFi = j.getCantidadFilas();
        int CantC = j.getCantidadColumnas();
        DefaultTableModel tb1 = (DefaultTableModel) this.tblCarton1.getModel();
        DefaultTableModel tb2 = (DefaultTableModel) this.tblCarton2.getModel();
        DefaultTableModel tb3 = (DefaultTableModel) this.tblCarton3.getModel();
        DefaultTableModel tb4 = (DefaultTableModel) this.tblCarton4.getModel();
        DefaultTableModel tb5 = (DefaultTableModel) this.tblCarton1.getModel();
        DefaultTableModel tb6 = (DefaultTableModel) this.tblCarton1.getModel();
        DefaultTableModel tb7 = (DefaultTableModel) this.tblCarton1.getModel();
        DefaultTableModel tb8 = (DefaultTableModel) this.tblCarton1.getModel();
        
        
        tb1.addColumn(CantC);
        tb2.addColumn(CantC);
        tb3.addColumn(CantC);
        tb4.addColumn(CantC);
        tb5.addColumn(CantC);
        tb6.addColumn(CantC);
        tb7.addColumn(CantC);
        tb8.addColumn(CantC);    
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vJugador().setVisible(true);
            }
        });
    }

    @Override
    public void update(Observable o, Object arg) {
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
